### ISSUE TITLE
License

### ISSUE THREAD

**Issue by italic-r** [JoseConseco/PivotPro#1]
Hi there. I'm just curious if you are distributing this under a license or not, and if so, which one. The reason I ask is because I would like to include it in our addons_extern repo: https://github.com/meta-androcto/blenderpython

If you choose to release it under a license, like GPL or Apache, etc, I am requesting a license block at the top of the file just to clear up confusion and make it absolutely clear. 

Thanks!

**Comment by JoseConseco** [comment]
I believe all blender addons have to gpl. 
I can't add license block right now, cos I have modified this addon on my pc, so I don't want to commit changes that would break compability with previous version. But you can do it if you really want.

**Comment by italic-r** [comment]
It doesn't necessarily have to be GPL, but it needs to be GPL-compatible, which could be Apache 2.0, Creative Commons, etc. I'll submit a pull request through github so you don't need to modify your local copy.
